### ISSUE TITLE
Getting an error when trying to use

### ISSUE THREAD

**Issue by txtcl0ud** [luijait/DarkGPT#16]
Hello, 

I'd those steps on kali. 

1) git clone https://github.com/luijait/DarkGPT.git 
cd DarkGPT
<img width="278" alt="image" src="https://github.com/luijait/DarkGPT/assets/124812753/5b901a5b-c6da-43ed-af19-1c704f0e3ce7">

2) cp .env.example .env
<img width="288" alt="image" src="https://github.com/luijait/DarkGPT/assets/124812753/5d4b8df0-2f4a-4335-9402-71dfcfbf7eb1">

3) pip install -r requirements.txt

4) python3 main.py 

I got this error:

hecho por: @luijait_

Bienvenido a DarkGPT una versión reducida del Agente de OSINT de nuestro modelo 0dAI un asistente que se sirve de GPT4 para hacer consultas en bases de datos e información filtrada escrito por @luijait_. Escribe 'exit' para terminar, 'clear' para limpiar la pantalla. Si quieres una versión mejorada de este agente y con funciones de pentesting autonomo y hacking, visita https://0dai.omegaai.io
> 
Traceback (most recent call last):
  File "/home/kali/DarkGPT/main.py", line 32, in <module>
    main()
  File "/home/kali/DarkGPT/main.py", line 28, in main
    conversational_shell.Start()
  File "/home/kali/DarkGPT/cli.py", line 35, in Start
    self.ProcessInput(user_input)
  File "/home/kali/DarkGPT/cli.py", line 59, in ProcessInput
    self.darkgpt.GPT_with_function_output(historial_json, callback=handle_chunk)
  File "/home/kali/DarkGPT/DarkAgent.py", line 83, in GPT_with_function_output
    function_output = self.execute_function_call(Leak_Function, historial[-1].get("USUARIO", ""))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/DarkGPT/DarkAgent.py", line 50, in execute_function_call
    response = self.openai_client.chat.completions.create(model="gpt-4",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

I'd generated api key on DEHASHED
My OpenIA account is 4.0 and have API key generated as well as the necessary access.\

Could you please help me?

**Comment by thetemplar1** [comment]
Having the same issue and haven't seen much response about this anywhere else online.

**Comment by jusso-dev** [comment]
Looks like the code is hard coded to pin to "gpt-4-1106-preview"

https://github.com/luijait/DarkGPT/blob/b0ed0be7da9b4c18364f89ac2e3c075221b8a625/DarkAgent.py#L34

I'll throw up a PR so this can be controlled via the .env file

In my experience using gpt-3.5-turbo should work fine.

**Comment by thetemplar1** [comment]
Jussi - Are you able to help add more details here on how this can be resolved? Seems to be an issue for others when searching. This could potentially be a great tool if this is resolved. I think providing details on how to resolve that would be great.

**Comment by jusso-dev** [comment]
Hey there, have you tried the latest code that's been merged? Also, have you experimented with different GPT versions as per the Open AI docs?

**Comment by thetemplar1** [comment]
I haven't experimented with other GPT models and haven't seen anything
anywhere that this is a confirmed fix, and which model to use.

I pulled about 3 weeks ago. I see there is a new update to DarkAgent. Is
that a fix?

Thanks

**Comment by jusso-dev** [comment]
Yes please review the latest code, adjust the GPT model and advise after you have tried all of these steps.

**Comment by thetemplar1** [comment]
Thanks jusso-dev. That works now. I have just tested though on my own email and it returned incorrect data - I have never used that password before! 

When searching for the leaked databases it appears these are fictitious too. 

I also asked what year the GPT data is trained on and it returned 2021. Is that correct? 

Thanks for your work on this.
