### ISSUE TITLE
.env.example 

### ISSUE THREAD

**Issue by gearcapitan** [luijait/DarkGPT#2]
the example file does not come, it is also not clear what else to put in that file ,env 

Traceback (most recent call last):
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/main.py", line 32, in <module>
    main()
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/main.py", line 28, in main
    conversational_shell.Start()
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/cli.py", line 35, in Start
    self.ProcessInput(user_input)
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/cli.py", line 59, in ProcessInput
    self.darkgpt.GPT_with_function_output(historial_json, callback=handle_chunk)
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/DarkAgent.py", line 83, in GPT_with_function_output
    function_output = self.execute_function_call(Leak_Function, historial[-1].get("USUARIO", ""))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hackmachine/Documentos/TOOLS/DarkGPT/DarkAgent.py", line 50, in execute_function_call
    response = self.openai_client.chat.completions.create(model="gpt-4",
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/resources/chat/completions.py", line 663, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by luijait** [comment]
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by luijait** [comment]
You should set OPENAI_API_KEY from https://openai.com and Dehashed login credentials just check .env 
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
