### ISSUE TITLE
HELP WITH THIS ISSUE

### ISSUE THREAD

**Issue by banerlord** [luijait/DarkGPT#20]
when i start the main.py
thats say my api keys is wrong but is the good one, what can i do ?

Traceback (most recent call last):
  File "C:\Windows\System32\DarkGPT\main.py", line 32, in <module>
    main()
  File "C:\Windows\System32\DarkGPT\main.py", line 24, in main
    darkgpt = DarkGPT()
              ^^^^^^^^^
  File "C:\Windows\System32\DarkGPT\DarkAgent.py", line 37, in __init__
    self.openai_client = Client(api_key=os.getenv("OPENAI_API_KEY"))  # Configuración del cliente OpenAI con la clave API.
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rez\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by jumbophp** [comment]
you didn't set the api key
