### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by GreenAA** [luijait/DarkGPT#35]
```
(venv) PS C:\Users\PycharmP\DarkGPT> python3 main.py
C:\Users\PycharmP\DarkGPT\main.py:11: SyntaxWarning: invalid escape sequence '\ '
  banner = """
Traceback (most recent call last):
  File "C:\Users\PycharmP\DarkGPT\main.py", line 1, in <module>
    from cli import parse_arguments, start_shell
  File "C:\Users\PycharmP\DarkGPT\cli.py", line 2, in <module>
    from darkgpt import GPT_with_function_output
  File "C:\Users\PycharmP\DarkGPT\darkgpt.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

```

**Comment by GreenAA** [comment]
answer , help  ?
