### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by r9z9cr7** [luijait/DarkGPT#4]
Hola, al clonar el repositorio no viene el archivo .env que se menciona para editar, y al crearlo con los parametros del example tampoco me funciona.

pip install -r requirements.txt                 
Collecting openai==1.13.3 (from -r requirements.txt (line 1))
  Using cached openai-1.13.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.31.0)
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

python3 main.py                                 
Traceback (most recent call last):
  File "/home/kali/DarkGPT/main.py", line 3, in <module>
    from DarkAgent import DarkGPT
  File "/home/kali/DarkGPT/DarkAgent.py", line 1, in <module>
    from openai import Client
ModuleNotFoundError: No module named 'openai'

no se si hago algun paso mal por si me puedes ayudar

**Comment by Evilander** [comment]
Did you install the dependencies?
